name: 'Terraform-Github-Destroy'

on:
  workflow_dispatch:

jobs:
  tf-destroy:
    name: 'Terraform'
    runs-on: ubuntu-latest   

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::026090537846:role/tfvideo40git-action

    - run: aws sts get-caller-identity

    - name: Terraform Init 
      run: terraform init

    - name: Terraform validate
      run: terraform validate
    
    - name: Terraform plan
      run: terraform plan -destroy

    - name: Terraform destroy
      run: terraform destroy -auto-approve